// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: CommandBuffer.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace redhatgamedev.srt
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CommandBuffer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public CommandBufferType Type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public SecurityCommandBuffer securityCommandBuffer { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public RawInputCommandBuffer rawInputCommandBuffer { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum CommandBufferType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
            Unknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SECURITY")]
            Security = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"RAWINPUT")]
            Rawinput = 2,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
